/**
 * All 55 alarm definitions with detection logic for FortiAnalyzer LogView API and vCenter.
 * Each alarm specifies: logtype, filter, threshold, timeWindowMinutes, and
 * optional clientCheck for post-fetch evaluation (e.g. off-hours detection).
 */

export interface CorrelationRule {
  precursorCodes: string[];      // Alarm codes that must have fired recently (step A)
  lookbackMinutes: number;       // How far back to look for precursor alarm events
  secondaryLogtype?: string;     // Optional: secondary FortiAnalyzer log search (step B)
  secondaryFilter?: string;      // Filter for secondary log search
  matchField: 'sourceIp' | 'destIp' | 'any'; // Field to correlate between step A and step B
  minDistinctCodes?: number;     // For multi-vector: minimum distinct alarm codes from same IP
}

export interface AlarmDetectionLogic {
  logtype?: string;            // FortiAnalyzer log type: event, attack, virus, dns, traffic, webfilter, app-ctrl (optional when source != fortianalyzer)
  filter?: string;             // FortiAnalyzer LogView filter expression (optional when source != fortianalyzer)
  threshold: number;           // Minimum count to trigger alarm
  timeWindowMinutes: number;   // How far back to search (minutes)
  clientCheck?: string;        // Optional client-side check: 'off-hours', 'brute-force-group', 'anomaly', 'geo-anomaly', 'correlation'
  fortiviewQuery?: string;     // Optional FortiView view name (instead of logview)
  correlationRules?: CorrelationRule; // Optional: correlation rules for SIEM-like detection
  source?: 'fortianalyzer' | 'fortigate-sslvpn' | 'vmware';  // Data source (default: fortianalyzer)
  description: string;         // Why this alarm matters
  recommendedAction: string;   // What operators should do
}

export interface AlarmDefinitionSeed {
  code: string;
  name: string;
  description: string;
  category: 'CONFIG_ACCESS' | 'SECURITY' | 'RISK_ANOMALY' | 'OPERATIONAL' | 'SOC_CORRELATION';
  severity: 'ALARM_CRITICAL' | 'ALARM_HIGH' | 'ALARM_MEDIUM' | 'ALARM_LOW' | 'ALARM_INFO';
  cooldownMinutes: number;
  notifyEmail?: boolean;
  detectionLogic: AlarmDetectionLogic;
}

export const ALARM_DEFINITIONS: AlarmDefinitionSeed[] = [
  // ============================================================================
  // CRITICAL - CONFIG & ACCESS
  // ============================================================================
  {
    code: 'FW_POLICY_CHANGED',
    name: 'Firewall Policy Degisikligi',
    description: 'Firewall kurallarinda ekleme, duzenleme veya silme tespit edildi. Kim tarafindan, nereden ve ne degistirildigini izler.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 180, // Must match timeWindowMinutes
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.policy%',
      threshold: 1,
      timeWindowMinutes: 180,
      description: 'Detects firewall policy add/edit/delete operations from system event logs. Includes admin user, source IP, and policy details.',
      recommendedAction: 'Verify change was authorized. Check admin identity and source IP. Review before/after policy state in config revisions.',
    },
  },
  {
    code: 'UNAUTH_ADMIN_LOGIN',
    name: 'Yetkisiz Admin Giris Denemesi',
    description: 'Beklenmeyen kullanici, IP veya yontemle admin giris denemesi tespit edildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 10,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and action == login and status == failed',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'Detects failed admin login attempts. Monitors unexpected users, IPs, or authentication methods.',
      recommendedAction: 'Investigate source IP and username. Check if this is a known admin. Block IP if suspicious. Enable 2FA if not already active.',
    },
  },
  {
    code: 'ADMIN_LOGIN_FAILED',
    name: 'Admin Basarisiz Giris Denemesi (FortiGate)',
    description: 'FortiGate uzerinden tespit edilen basarisiz admin giris denemesi.',
    category: 'SECURITY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 5,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and action == login and status == failed',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'Detects failed admin login attempts directly from FortiGate REST API. Monitors all authentication failures regardless of user or IP.',
      recommendedAction: 'Review source IP and username. Verify if this is a legitimate admin. Consider blocking IP after multiple failures. Enable 2FA for all admin accounts.',
    },
    notifyEmail: true,
  },
  {
    code: 'ADMIN_LOGIN_OFF_HOURS',
    name: 'Mesai Disi Admin Girisi',
    description: 'Calisma saatleri disinda (08:00-18:00) admin girisi tespit edildi. Hafta sonu ve tatil gunleri vurgulanir.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and action == login and status == success',
      threshold: 1,
      timeWindowMinutes: 10,
      clientCheck: 'off-hours',
      description: 'Detects admin logins outside business hours (08:00-18:00 weekdays). Weekends and holidays flagged as higher risk.',
      recommendedAction: 'Confirm login was planned/authorized. If unexpected, investigate immediately. Check what changes were made during off-hours session.',
    },
  },
  {
    code: 'CORE_CONFIG_CHANGE',
    name: 'Kritik Yapilandirma Degisikligi',
    description: 'Interface, routing, HA veya system-level degisiklikler tespit edildi. Risk etkisi yuksek.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 180, // Must match timeWindowMinutes to prevent duplicate triggers
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% or logdesc like %changed%',
      threshold: 1,
      timeWindowMinutes: 180,
      description: 'Detects configuration changes to core settings: interfaces, routing tables, HA configuration, and system-level parameters. Matches both "Object attribute configured" and "Configuration changed" log types.',
      recommendedAction: 'Review change details in config revisions. Verify authorized change window. Assess blast radius - did change affect redundancy or routing?',
    },
  },
  {
    code: 'FIRMWARE_CHANGE',
    name: 'Firmware Upgrade/Downgrade',
    description: 'FortiGate firmware versiyonu degisikligi tespit edildi. Downgrade daha yuksek risk olarak isaretlenir.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %firmware%',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Detects FortiGate firmware version changes. Downgrades are flagged as higher risk due to potential vulnerability reintroduction.',
      recommendedAction: 'Verify firmware change was planned. If downgrade, investigate reason. Ensure backup was taken before change. Validate HA synchronization.',
    },
  },
  // ============================================================================
  // HIGH - SECURITY FOCUSED
  // ============================================================================
  {
    code: 'VPN_BRUTE_FORCE',
    name: 'VPN Brute Force Denemesi',
    description: 'Kisa surede birden fazla basarisiz VPN giris denemesi (SSL/IPsec). Ayni kaynak IP veya birden fazla kullanici.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and action == ssl-login-fail',
      // Previously: 'subtype == vpn and status == failed' — status field not set for ssl-login-fail events
      threshold: 5,
      timeWindowMinutes: 15,
      clientCheck: 'brute-force-group',
      description: 'Detects VPN brute force attacks: multiple failed SSL-VPN or IPsec login attempts in short time window. Groups by source IP.',
      recommendedAction: 'Block source IP at firewall. Check if credentials compromised. Review VPN authentication policies. Consider rate limiting.',
    },
  },
  {
    code: 'VPN_LOGIN_OFF_HOURS',
    name: 'Mesai Disi SSL-VPN Baglantisi',
    description: 'Calisma saatleri disinda (08:00-18:00) veya hafta sonu SSL-VPN baglantisi tespit edildi. Yetkisiz uzaktan erisim riski.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 240,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == user and action == auth-logon',
      threshold: 1,
      timeWindowMinutes: 240,       // Look back 4 hours to catch sessions missed by earlier cycles
      clientCheck: 'off-hours',
      source: 'fortigate-sslvpn',   // Primary: FortiGate API for currently active sessions
      description: 'Detects SSL-VPN connections outside business hours (08:00-18:00 weekdays). Uses FortiGate API for real-time active session detection. Alarm fires once per user per 4 hours.',
      recommendedAction: 'Verify VPN user identity and authorization. Check if remote work was planned. Review accessed resources during off-hours session. Contact user if unexpected.',
    },
  },
  {
    code: 'SSLVPN_BUSINESS_HOURS',
    name: 'SSL-VPN Mesai Içi Baglantisi',
    description: 'Calisma saatleri içinde (08:00-18:00) ve hafta içi SSL-VPN baglantisi tespit edildi. Normal çalışma saatlerinde beklenen bağlantı.',
    category: 'SECURITY',
    severity: 'ALARM_INFO',
    cooldownMinutes: 60,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'event',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 60,
      clientCheck: 'business-hours',
      source: 'fortigate-sslvpn',  // Use FortiGate API directly for SSL-VPN users
      description: 'Detects SSL-VPN connections during business hours (08:00-18:00 weekdays). Informational only - tracks normal VPN usage.',
      recommendedAction: 'Review user activity for any suspicious behavior. This is expected VPN usage during work hours.',
    },
  },
  {
    code: 'USER_SESSION_OFF_HOURS',
    name: 'Mesai Disi Kullanici Oturumu',
    description: 'Calisma saatleri disinda (18:00-08:00) veya hafta sonu kullanici oturumu acildi. Yetkisiz erisim riski.',
    category: 'SECURITY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'traffic',
      filter: 'action == accept',
      threshold: 1,
      timeWindowMinutes: 60,
      clientCheck: 'off-hours',
      description: '18:00-08:00 arasi veya hafta sonu kullanici oturumu acilmasini tespit eder. Yetkisiz erisim veya planli olmayan calisma gostergesi.',
      recommendedAction: 'Kullanici kimligini dogrulayin. Oturum neden acildi arastirin. Erisilen kaynaklari kontrol edin. Planli calisma ise onaylayin.',
    },
  },
  {
    code: 'ADMIN_BRUTE_FORCE',
    name: 'Admin Brute Force Denemesi',
    description: 'Esik degerini asan basarisiz admin giris denemeleri tespit edildi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and action == login and status == failed',
      threshold: 5,
      timeWindowMinutes: 15,
      clientCheck: 'brute-force-group',
      description: 'Threshold-based brute force detection for admin logins. Triggers when failed count exceeds threshold in time window.',
      recommendedAction: 'Block source IP. Verify admin account integrity. Enable account lockout policy. Review admin access control list.',
    },
  },
  {
    code: 'IPS_CRITICAL_ALERT',
    name: 'IPS Kritik Seviye Alarm',
    description: 'Exploit imzalari, CVE ile iliskili olaylar tespit edildi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 10,
    detectionLogic: {
      logtype: 'attack',
      filter: 'severity == critical',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Detects critical/high severity IPS alerts including exploit signatures and CVE-related events.',
      recommendedAction: 'Investigate targeted system. Check if exploit was successful. Patch vulnerable systems. Review IPS signature updates.',
    },
  },
  {
    code: 'MALWARE_DETECTED',
    name: 'Malware Tespit Edildi',
    description: 'Antivirus tarafindan kotu amacli yazilim tespit edildi ve engellendi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 10,
    detectionLogic: {
      logtype: 'virus',
      filter: 'action == blocked',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Detects malware/antivirus detections with severity context. Tracks blocked threats and their source.',
      recommendedAction: 'Identify infected host. Run full AV scan on endpoint. Check for lateral movement. Review web filtering policies.',
    },
  },
  {
    code: 'DNS_MALICIOUS',
    name: 'Zararli DNS Istegi Engellendi',
    description: 'Bilinen zararli domain veya C2 trafigi tespit ve engellendi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 10,
    detectionLogic: {
      logtype: 'dns',
      filter: 'action == blocked',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Detects blocked DNS requests to known malicious domains, C2 servers, and threat intelligence-flagged FQDNs.',
      recommendedAction: 'Identify requesting host. Check for malware infection. Block domain at multiple layers. Update threat intelligence feeds.',
    },
  },
  // ============================================================================
  // MEDIUM - RISK & ANOMALY
  // ============================================================================
  {
    code: 'NEW_SERVICE_OBJECT',
    name: 'Yeni Firewall Servis Nesnesi',
    description: 'Yeni port veya protokol tanimlandi. Shadow IT veya yetkisiz servis acilisi olabilir.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.service% and action == Add',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Detects creation of new firewall service objects (ports/protocols). New services may introduce attack surface.',
      recommendedAction: 'Review new service object. Verify it was requested through change management. Check if port is commonly exploited.',
    },
  },
  {
    code: 'NEW_ADDRESS_OBJECT',
    name: 'Yeni Firewall Adres Nesnesi',
    description: 'Yeni IP, subnet veya FQDN nesnesi olusturuldu.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60, // Must match timeWindowMinutes
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.address% and action == Add',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Detects new firewall address objects (IP, subnet, FQDN). Unauthorized additions may expose internal resources.',
      recommendedAction: 'Verify address object was authorized. Check if it bypasses existing security policies. Review associated policy references.',
    },
  },
  {
    code: 'ADDRESS_OBJECT_CHANGED',
    name: 'Firewall Adres Nesnesi Degistirildi',
    description: 'Mevcut IP, subnet veya FQDN nesnesi duzenlendi veya silindi. Politika etkisi incelenmeli.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 60, // Must match timeWindowMinutes
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.address%',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Detects firewall address object modifications (Edit/Delete). Changes to address objects can affect multiple policies.',
      recommendedAction: 'Review changed address object and identify all policies referencing it. Verify change was authorized. Check before/after values.',
    },
  },
  {
    code: 'POLICY_HIT_ANOMALY',
    name: 'Policy Hit Rate Anomalisi',
    description: 'Baseline degerine gore ani trafik artisi tespit edildi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1000,
      timeWindowMinutes: 15,
      clientCheck: 'anomaly',
      description: 'Detects sudden traffic increase compared to baseline. May indicate DDoS, data exfiltration, or compromised host.',
      recommendedAction: 'Identify top talkers and affected policies. Compare with historical baseline. Check for DDoS indicators. Review bandwidth usage.',
    },
  },
  {
    code: 'EXCESSIVE_BANDWIDTH',
    name: 'Tek Host Asiri Bant Genisligi',
    description: 'Tek bir host normalin cok ustunde bant genisligi kullaniyor.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 15,
      fortiviewQuery: 'top-sources',
      clientCheck: 'anomaly',
      description: 'Top talker anomaly detection. Identifies single hosts consuming excessive bandwidth that may indicate data exfiltration.',
      recommendedAction: 'Identify the host and user. Check application usage. Verify if legitimate (backup, update) or suspicious (exfiltration).',
    },
  },
  {
    code: 'APP_CONTROL_VIOLATION',
    name: 'Uygulama Kontrol Ihlali',
    description: 'Engellenen veya kisitlanan uygulama kullanimi tespit edildi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'app-ctrl',
      filter: 'action == blocked',
      threshold: 5,
      timeWindowMinutes: 15,
      description: 'Detects blocked or restricted application usage. Frequent violations may indicate policy bypass attempts or shadow IT.',
      recommendedAction: 'Review blocked applications. Identify users/hosts. Update application control policies if needed. Address shadow IT concerns.',
    },
  },
  // ============================================================================
  // LOW - OPERATIONAL
  // ============================================================================
  {
    code: 'INTERFACE_FLAP',
    name: 'Interface Down/Up',
    description: 'Link flap veya interface instabilitesi tespit edildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %link%',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Detects interface link state changes (up/down flaps). May indicate cable, SFP, or switch port issues.',
      recommendedAction: 'Check physical connectivity. Review switch port status. Monitor for recurring flaps. Check SFP module health.',
    },
  },
  {
    code: 'VPN_TUNNEL_DOWN',
    name: 'VPN Tunnel Down',
    description: 'IPsec veya SSL tunnel kesintisi tespit edildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 15,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and action == tunnel-down',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Detects IPsec or SSL-VPN tunnel interruptions. Affects remote site connectivity and user access.',
      recommendedAction: 'Check remote peer status. Verify internet connectivity at both ends. Review Phase 1/2 SA negotiation logs. Restart tunnel if needed.',
    },
  },
  {
    code: 'HIGH_CPU_MEMORY',
    name: 'Yuksek CPU/Memory Kullanimi',
    description: 'Surdurulebilir esik degeri asimi tespit edildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %conserve%',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'Detects sustained high CPU or memory usage. FortiGate enters conserve mode when resources are critically low.',
      recommendedAction: 'Check current CPU/memory via dashboard. Identify resource-heavy processes. Review session count. Consider traffic optimization.',
    },
  },
  {
    code: 'DISK_USAGE_HIGH',
    name: 'Disk Kullanimi Yuksek',
    description: '%80 uyari, %90 kritik disk doluluk esigi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %disk%',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Detects disk usage exceeding thresholds. 80% warning, 90% critical. Affects logging and system stability.',
      recommendedAction: 'Check disk usage on device. Clear old logs if needed. Verify log rotation settings. Consider expanding storage.',
    },
  },
  {
    code: 'DEVICE_REBOOT',
    name: 'FortiGate Reboot Tespit Edildi',
    description: 'Beklenmedik yeniden baslatma veya crash tespit edildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %restart%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Detects unexpected reboots or crashes. Planned reboots should be in change window.',
      recommendedAction: 'Check if reboot was planned. Review crash logs. Verify HA failover occurred correctly. Check uptime after reboot.',
    },
  },
  // ============================================================================
  // ADVANCED - SOC CORRELATION
  // ============================================================================
  {
    code: 'CONFIG_THEN_SPIKE',
    name: 'Config Degisikligi Sonrasi Trafik Artisi',
    description: 'Yapilandirma degisikligi ile trafik anomalisi arasinda zamansal korelasyon.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and action == config-change',
      threshold: 1,
      timeWindowMinutes: 15,
      clientCheck: 'anomaly',
      description: 'Temporal correlation between config change and traffic anomaly. Change followed by spike may indicate malicious modification.',
      recommendedAction: 'Review the config change that preceded the spike. Check if new policy allows unwanted traffic. Correlate with user activity.',
    },
  },
  {
    code: 'ADMIN_NEW_GEO',
    name: 'Yeni Ulke/IP\'den Admin Girisi',
    description: 'Daha once gorulmemis Geo-IP veya ASN anomalisi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and action == login and status == success',
      threshold: 1,
      timeWindowMinutes: 15,
      clientCheck: 'geo-anomaly',
      description: 'Detects admin logins from previously unseen countries or IP ranges. May indicate credential compromise or VPN proxy.',
      recommendedAction: 'Verify admin identity. Check if VPN/proxy is in use. Cross-reference with known admin locations. Force password reset if suspicious.',
    },
  },
  {
    code: 'MULTI_SECURITY_EVENTS',
    name: 'Ayni Kaynaktan Coklu Guvenlik Olaylari',
    description: 'Tek bir IP/host\'tan korelasyonlu saldirilar tespit edildi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'attack',
      filter: '',
      threshold: 10,
      timeWindowMinutes: 15,
      clientCheck: 'brute-force-group',
      description: 'Correlated attack detection from single source IP/host. Multiple security events indicate coordinated attack.',
      recommendedAction: 'Block source IP immediately. Investigate all affected targets. Check for lateral movement. Create threat intelligence entry.',
    },
  },
  {
    code: 'SECURITY_PROFILE_DISABLED',
    name: 'Guvenlik Profili Devre Disi',
    description: 'IPS, AV, WebFilter devre disi birakildi veya bypass edildi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 5,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %security%',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Detects when security profiles (IPS, AV, WebFilter) are disabled or bypassed. Critical gap in defense.',
      recommendedAction: 'Immediately verify if change was authorized. Re-enable security profiles. Investigate who made the change and why. Audit affected traffic window.',
    },
  },
  {
    code: 'SHADOW_IT_DETECTED',
    name: 'Shadow IT Tespiti',
    description: 'Daha once gorulmemis uygulama veya servisler tespit edildi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'app-ctrl',
      filter: 'action == detected',
      threshold: 3,
      timeWindowMinutes: 30,
      description: 'Detects previously unseen applications or services. Shadow IT introduces unmanaged risk.',
      recommendedAction: 'Identify applications and users. Assess risk of new applications. Update application control policies. Educate users on IT policy.',
    },
  },
  // ============================================================================
  // NEW - WEBFILTER
  // ============================================================================
  {
    code: 'WEBFILTER_HIGH_RISK',
    name: 'Yuksek Riskli Web Erisim',
    description: 'Malware, phishing, proxy-avoidance gibi yuksek riskli kategorilere erisim denemesi tespit edildi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'webfilter',
      filter: 'action == blocked',
      threshold: 3,
      timeWindowMinutes: 15,
      description: 'WebFilter tarafindan engellenen yuksek riskli web kategorilerine (malware, phishing, proxy atlama vb.) erisim denemelerini tespit eder.',
      recommendedAction: 'Kullanici ve hostu belirleyin. Malware enfeksiyonu kontrolu yapin. Tarama gecmisini inceleyin. Birden fazla deneme varsa endpoint taramasi baslatmayi degerlendiriniz.',
    },
  },
  {
    code: 'WEBFILTER_OVERRIDE',
    name: 'WebFilter Bypass/Override',
    description: 'Kullanici veya admin tarafindan WebFilter kurali bypass edildi veya override yapildi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'webfilter',
      filter: 'action == passthrough',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'WebFilter politikasinin bypass edilmesini veya override islemlerini tespit eder. Engellenmis iceriklere yetkisiz erisim gostergesi olabilir.',
      recommendedAction: 'Override iznini kimin verdigini kontrol edin. Hedef URL/domaini inceleyin. Override in gecici ve gerekce ile yapildigini dogrulayin.',
    },
  },
  // ============================================================================
  // NEW - TRAFFIC ANOMALY
  // ============================================================================
  {
    code: 'DENIED_TRAFFIC_SPIKE',
    name: 'Engellenen Trafik Artisi',
    description: 'Deny edilen trafik sayisinda ani artis tespit edildi. Port taramasi veya saldiri gostergesi olabilir.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'traffic',
      filter: 'action == deny',
      threshold: 50,
      timeWindowMinutes: 15,
      description: 'Engellenen trafik sayisinda ani artisi tespit eder. Port taramasi, brute force veya DDoS denemesi gostergesi olabilir.',
      recommendedAction: 'Engellenen trafikteki kaynak IP leri belirleyin. Tarama veya saldiri kalibini kontrol edin. Israrci kaynaklari cevre guvenlik duvarinda engelleyin.',
    },
  },
  {
    code: 'DATA_EXFIL_SUSPECT',
    name: 'Veri Sizintisi Suphesi',
    description: 'Tek bir hosttan disariya yuksek hacimde veri transferi tespit edildi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      fortiviewQuery: 'top-sources',
      clientCheck: 'anomaly',
      description: 'Tek bir hosttan disariya yuksek hacimde veri transferini tespit eder. Veri sizintisi veya ele gecirilmis sistem gostergesi olabilir.',
      recommendedAction: 'Hostu ve hedefi belirleyin. Transferin meşru olup olmadigini kontrol edin (yedekleme, senkronizasyon). Kullanici aktivitesini araştırın. Yetkisizse engelleyin.',
    },
  },
  {
    code: 'UNUSUAL_COUNTRY_TRAFFIC',
    name: 'Olagan Disi Ulke Trafigi',
    description: 'Normalde gorulmeyen ulkelere veya ulkelerden gelen trafik anomalisi tespit edildi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      fortiviewQuery: 'top-countries',
      clientCheck: 'geo-anomaly',
      description: 'Baseline disinda kalan ulkelere/ulkelerden gelen trafigi tespit eder. Ele gecirilmis host veya yetkisiz iletisim gostergesi olabilir.',
      recommendedAction: 'Hedef ulkeleri inceleyin. Is gereksinimiyle uyumlu olup olmadigini kontrol edin. Suphe yaratan ulke trafigini geo-IP politikalariyla engelleyin.',
    },
  },
  {
    code: 'HIGH_SESSION_COUNT',
    name: 'Asiri Oturum Sayisi',
    description: 'Tek bir IP adresinden cok sayida esanli oturum tespit edildi. Botnet veya DDoS gostergesi olabilir.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 15,
      fortiviewQuery: 'top-sources',
      clientCheck: 'anomaly',
      description: 'Tek bir IP den anormal derecede yuksek oturum sayisini tespit eder. Botnet aktivitesi, DDoS veya yanlis yapilandirilmis uygulama gostergesi olabilir.',
      recommendedAction: 'Kaynak hostu belirleyin. Calisan surecler ve servisleri kontrol edin. Oturum limitlerini uygulayin. Botnet suphesi varsa izole edin.',
    },
  },
  // ============================================================================
  // NEW - HA / REDUNDANCY
  // ============================================================================
  {
    code: 'HA_FAILOVER',
    name: 'HA Failover Tespit Edildi',
    description: 'FortiGate HA cluster aktif-pasif gecis tespit edildi. Servis kesintisi riski.',
    category: 'OPERATIONAL',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == ha',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'HA failover olaylarini tespit eder. Aktif-pasif gecis kisa sureli servis kesintisine neden olabilir.',
      recommendedAction: 'Her iki HA peer i kontrol edin. Servislerin kurtarildigini dogrulayin. Failover nedenini araştırın. HA senkronizasyonunun stabil oldugunu dogrulayin.',
    },
  },
  {
    code: 'HA_CONFIG_SYNC_FAIL',
    name: 'HA Config Senkronizasyon Hatasi',
    description: 'HA peerlar arasi konfigurasyon senkronizasyonu basarisiz oldu. Cluster uyumsuzlugu riski.',
    category: 'OPERATIONAL',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == ha and logdesc like %out of sync%',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'HA cluster peerlari arasindaki konfigurasyon senkronizasyon hatalarini tespit eder. Uyumsuz konfigurasyonlar failover sirasinda tutarsizlik riski olusturur.',
      recommendedAction: 'HA senkronizasyon durumunu kontrol edin. Gerekirse manuel senkronizasyon zorlayın. Her iki peer in ayni konfigurasyona sahip oldugunu dogrulayin. Heartbeat baglantisini kontrol edin.',
    },
  },
  // ============================================================================
  // NEW - DNS
  // ============================================================================
  {
    code: 'DNS_TUNNEL_SUSPECT',
    name: 'DNS Tunelleme Suphesi',
    description: 'Tek bir domaine asiri DNS sorgusu tespit edildi. DNS tunelleme veya C2 haberlesme gostergesi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'dns',
      filter: '(srcip != 10.5.2.1 and srcip != 10.5.2.2) and (dstip != 8.8.8.8 and dstip != 8.8.4.4 and dstip != 1.1.1.1 and dstip != 1.0.0.1 and dstip != 208.67.222.222 and dstip != 208.67.220.220 and dstip != 195.175.39.39 and dstip != 195.175.39.40)',
      threshold: 50,
      timeWindowMinutes: 15,
      clientCheck: 'brute-force-group',
      description: 'Tek bir domaine asiri DNS sorgusunu tespit eder. Bilindik DNS sunuculari (Google, Cloudflare, OpenDNS) ve dahili DNS sunuculari (10.5.2.1, 10.5.2.2) haric tutulur. Yuksek sorgu hacmi DNS tunelleme veya C2 haberlesme gostergesi olabilir.',
      recommendedAction: 'Sorgulanan domaini ve kaynak hostu belirleyin. DNS tunelleme araclari kontrol edin. Suphe yaratan domaini engelleyin. Endpoint i malware taramasindan gecirin.',
    },
  },
  // ============================================================================
  // NEW - CONFIG DETAIL
  // ============================================================================
  {
    code: 'ADDRESS_GROUP_CHANGED',
    name: 'Adres Grubu Degisikligi',
    description: 'Firewall adres grubu (address group) uzerinde ekleme, silme veya duzenleme tespit edildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.addrgrp%',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Firewall adres gruplarina yapilan degisiklikleri tespit eder. Grup degisiklikleri birden fazla politikayi ayni anda etkileyebilir.',
      recommendedAction: 'Hangi adres grubunun degistigini inceleyin. Bu grubu referans alan tum politikalari kontrol edin. Degisikligin change management ile onaylandigini dogrulayin.',
    },
  },
  {
    code: 'ADMIN_PRIVILEGE_CHANGE',
    name: 'Admin Yetki Degisikligi',
    description: 'Admin profili veya yetkilendirme ayarlari degistirildi. Privilege escalation riski.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %system.admin%',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Admin profillerine, yetkilerine veya erisim ayarlarina yapilan degisiklikleri tespit eder. Yetki yukseltme girisimi gostergesi olabilir.',
      recommendedAction: 'Degisikligi kimin yaptigini dogrulayin. Hangi yetkilerin degistirildigini kontrol edin. Admin oturum loglarini inceleyin. En az yetki ilkesini uygulayın.',
    },
  },
  {
    code: 'ROUTE_TABLE_CHANGED',
    name: 'Routing Tablosu Degisikligi',
    description: 'Statik veya dinamik route degisikligi tespit edildi. Trafik yonlendirme uzerinde etkisi olabilir.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %router%',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Statik/dinamik routing tablosu degisikliklerini tespit eder. Route degisiklikleri trafik akisini etkiler ve kesintilere neden olabilir.',
      recommendedAction: 'Route degisiklik detaylarini inceleyin. Trafik akisinin dogru oldugunu dogrulayin. Routing donguleri kontrol edin. Kritik hedeflere baglanti testleri yapin.',
    },
  },
  // ============================================================================
  // NEW - SSL-VPN
  // ============================================================================
  {
    code: 'VPN_NEW_USER',
    name: 'Yeni SSL-VPN Kullanicisi',
    description: 'Daha once gorulmemis bir kullanici ile SSL-VPN baglantisi tespit edildi.',
    category: 'SECURITY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == user and action == auth-logon',
      // Previously: 'subtype == vpn and action != negotiate and status == success' — no matching logs
      // FortiGate user auth events use subtype=user, action=auth-logon
      threshold: 1,
      timeWindowMinutes: 30,
      clientCheck: 'geo-anomaly',
      description: 'Daha once gorulmemis kullanicilardan VPN baglantisini tespit eder. Yeni VPN kullanicilari yetkisiz erisim gostergesi olabilir.',
      recommendedAction: 'Kullanici kimligini ve yetkilendirmesini dogrulayin. Hesabin yakın zamanda olusturulup olusturulmadigini kontrol edin. Kullanici icin VPN erisim politikalarini inceleyin.',
    },
  },
  // ============================================================================
  // SSL-VPN CONNECTION MONITORING
  // ============================================================================
  {
    code: 'SSLVPN_CONNECTION',
    name: 'SSL-VPN Baglanti Tespit Edildi',
    description: 'Yeni SSL-VPN baglantisi tespit edildi. Kullanici, kaynak IP, interface ve baglanti detaylari kaydedilir.',
    category: 'SECURITY',
    severity: 'ALARM_INFO',
    cooldownMinutes: 60,           // Per-user cooldown — same user won't re-alarm within 60 min
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == user and action == auth-logon',
      threshold: 1,
      timeWindowMinutes: 60,        // Capture all connections in the last 60 min
      clientCheck: 'per-user-dedup',// Fire one alarm per user, skip users already alerted
      description: 'SSL-VPN basarili girislerini tespit eder. Her yeni baglanti icin kullanici bilgileri, kaynak IP ve baglanti detaylari kaydedilir.',
      recommendedAction: 'Baglantiyi dogrulayin. Beklenmeyen kullanicilar veya lokasyonlar icin kullanici ile iletisime gecin.',
    },
  },
  {
    code: 'SSLVPN_AUTH_FAILED',
    name: 'SSL-VPN Giris Hatasi',
    description: 'SSL-VPN giris denemesi basarisiz oldu. Yanlis sifre veya kullanici adi hatasi.',
    category: 'SECURITY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 10,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and action == ssl-login-fail',
      // Previously: 'subtype == vpn and status == failed' — status field not set for ssl-login-fail events
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'SSL-VPN basarisiz giris denemelerini tespit eder. Yanlis sifre, gecersiz kullanici veya sertifika hatalari dahil.',
      recommendedAction: 'Kaynak IP ve kullanici adini kontrol edin. Birden fazla hatali deneme varsa brute force suphesi arastirin. Kullanicinin sifreyi degistirmesi gerekebilir.',
    },
  },
  {
    code: 'SSLVPN_MULTI_FAIL',
    name: 'SSL-VPN Coklu Hatali Giris',
    description: 'Ayni kaynak IP den veya kullanicidan kisa surede birden fazla basarisiz giris denemesi. Brute force saldirisi veya unuttum-sifre durumu.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and action == ssl-login-fail',
      // Previously: 'subtype == vpn and status == failed' — status field not set for ssl-login-fail events
      threshold: 3,
      timeWindowMinutes: 10,
      clientCheck: 'brute-force-group',
      description: 'Kisa surede ayni IP veya kullanicidan 3+ basarisiz giris tespiti. Brute force saldirisi veya hesap sorunlari gostergesi.',
      recommendedAction: 'Kaynak IP yi gecici olarak engelleyin. Kullanici hesabini kontrol edin. Hesap kilitlenmis mi dogrulayin. Israrci saldiri varsa kalici engelleme uygulayın.',
    },
  },
  {
    code: 'SSLVPN_LOCKOUT',
    name: 'SSL-VPN Hesap Kilitlendi',
    description: 'Tekrarlanan basarisiz giris denemeleri nedeniyle SSL-VPN hesabi kilitlendi.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and logdesc like %lockout%',
      // Previously: 'subtype == auth and action == auth-lockout' — no events with subtype=auth
      // FortiGate lockout events are under subtype=vpn with lockout in logdesc
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'SSL-VPN hesap kilitleme olaylarini tespit eder. Brute force saldirisi veya kullanici sifresi sorunu gostergesi.',
      recommendedAction: 'ACIL: Hesap sahibi ile iletisime gecin. Yetkisiz erisim denemesi mi yoksa kullanici hatasi mi belirleyin. Kaynak IP yi inceleyin ve gerekirse engelleyin.',
    },
  },
  {
    code: 'SSLVPN_TUNNEL_UP',
    name: 'SSL-VPN Tunel Aktif',
    description: 'SSL-VPN tunnel oturumu basarili sekilde kuruldu. Baglanti kalitesi ve veri transferi izlenir.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 15,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and action == tunnel-up',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'SSL-VPN tunnel kurulum olaylarini tespit eder. Baglanti suresi ve veri transferi metriklerini kaydeder.',
      recommendedAction: 'Normal operasyon olarak kabul edin. Beklenmeyen lokasyonlardan tunnel kurulumu varsa arastirin.',
    },
  },
  {
    code: 'SSLVPN_TUNNEL_DOWN',
    name: 'SSL-VPN Tunel Kapandi',
    description: 'SSL-VPN tunnel oturumu sonlandirildi veya koptu.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 15,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == vpn and action == tunnel-down',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'SSL-VPN tunnel sonlandirma olaylarini tespit eder. Normal kapanis, timeout veya baglanti kesintisi olabilir.',
      recommendedAction: 'Tekrarlayan beklenmedik kapanislar icin network baglantisini kontrol edin. Session timeout ayarlarini gozden gecirin.',
    },
  },
  {
    code: 'SSLVPN_HIGH_TRAFFIC',
    name: 'SSL-VPN Yuksek Trafik Tespit Edildi',
    description: 'Tek bir SSL-VPN oturumundan anormal derecede yuksek veri transferi. Veri sizintisi veya normal is yukunun ustunde kullanim.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'traffic',
      filter: 'action == accept and tunneltype == ssl-web',
      threshold: 1,
      timeWindowMinutes: 30,
      clientCheck: 'anomaly',
      description: 'SSL-VPN uzerinden normal ustunde veri transferini tespit eder. Data exfiltration veya yetkisiz buyuk dosya indirme gostergesi.',
      recommendedAction: 'Kullanici aktivitesini inceleyin. Transfer edilen veri turlerini belirleyin. Suphe yaratan durumlarda oturumu sonlandirin.',
    },
  },
  // ============================================================================
  // NEW - FORTIVIEW INTELLIGENCE
  // ============================================================================
  {
    code: 'TOP_THREAT_WEIGHT',
    name: 'En Yuksek Tehdit Skoru',
    description: 'FortiView top-threats analizinde kritik seviye tehdit skoru tespit edildi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'attack',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      fortiviewQuery: 'top-threats',
      clientCheck: 'anomaly',
      description: 'FortiView top-threats analizinde kritik tehdit agirlik skorlarini izler. Yuksek skorlar aktif sofistike saldirilari gosterir.',
      recommendedAction: 'Tehdit kaynagini ve hedefini araştırın. Saldirinin engellenip engellenmedigini kontrol edin. IPS imzalarini guncelleyin. Tehdit gostergeleri icin IoC kaydi olusturun.',
    },
  },
  {
    code: 'RISKY_CLOUD_APP',
    name: 'Riskli Bulut Uygulamasi',
    description: 'FortiView top-cloud-applications analizinde yuksek riskli bulut uygulamasi kullanimi tespit edildi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'app-ctrl',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      fortiviewQuery: 'top-cloud-applications',
      clientCheck: 'anomaly',
      description: 'FortiView uzerinden yuksek riskli bulut uygulamasi kullanimini tespit eder. Riskli uygulamalar veri sizintisina veya uyumluluk ihlallerine yol acabilir.',
      recommendedAction: 'Kullanicilari ve riskli uygulamalari belirleyin. Is ihtiyacini degerlendirin. Yetkisiz bulut uygulamalarini engelleyin. Uygulama kontrol politikalarini guncelleyin.',
    },
  },
  // ============================================================================
  // CORRELATION - SIEM-LIKE CROSS-REFERENCE ALARMS
  // ============================================================================
  {
    code: 'BRUTE_THEN_SUCCESS',
    name: 'Brute Force Sonrasi Basarili Giris',
    description: 'Ayni IP den brute force denemesi ardindan basarili giris tespit edildi. Kimlik bilgilerinin ele gecirilmis olma ihtimali yuksek.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: ['ADMIN_BRUTE_FORCE', 'VPN_BRUTE_FORCE'],
        lookbackMinutes: 30,
        secondaryLogtype: 'event',
        secondaryFilter: 'subtype == system and action == login and status == success',
        matchField: 'sourceIp',
      },
      description: 'Brute force alarmi tetiklenen IP den ardindan basarili giris tespit eder. Kimlik bilgisi ele gecirilmis olabilir.',
      recommendedAction: 'Hesabi derhal devre disi birakin. Sifre sifirlamasi zorunlu kilin. Kaynak IP yi kalici olarak engelleyin. Oturumda yapilan islemleri inceleyin.',
    },
  },
  {
    code: 'SSLVPN_BRUTE_THEN_SUCCESS',
    name: 'SSL-VPN Brute Force Sonrasi Basarili Giris',
    description: 'Ayni IP den SSL-VPN brute force saldirisi ardindan basarili giris tespit edildi. Kimlik bilgileri ele gecirilmis olabilir.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 30,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'event',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: ['SSLVPN_MULTI_FAIL', 'VPN_BRUTE_FORCE', 'SSLVPN_LOCKOUT'],
        lookbackMinutes: 30,
        secondaryLogtype: 'event',
        secondaryFilter: 'subtype == user and action == auth-logon',
        // Previously: 'subtype == auth and action == auth-logon' — no events with subtype=auth
        matchField: 'sourceIp',
      },
      description: 'SSL-VPN brute force veya coklu hatali giris alarmi tetiklenen IP den ardindan basarili VPN giris tespit eder. Hesap ele gecme gostergesi.',
      recommendedAction: 'ACIL: VPN oturumunu derhal sonlandirin. Kullanici hesabini kilitleyin. Kaynak IP yi kalici olarak engelleyin. Hesap aktivitelerini ve erisilen kaynaklari inceleyin. Sifre degisikligi zorunlu kilin.',
    },
  },
  {
    code: 'LOGIN_THEN_CONFIG',
    name: 'Giris Sonrasi Hizli Config Degisikligi',
    description: 'Admin girisi ardindan kisa sure icinde yapilandirma degisikligi tespit edildi. Ic tehdit zinciri gostergesi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 15,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: ['ADMIN_LOGIN_OFF_HOURS', 'ADMIN_NEW_GEO', 'UNAUTH_ADMIN_LOGIN'],
        lookbackMinutes: 15,
        secondaryLogtype: 'event',
        secondaryFilter: 'subtype == system and logdesc like %attribute%',
        matchField: 'sourceIp',
      },
      description: 'Suphe yaratan admin girisi (mesai disi, yeni geo, yetkisiz) ardindan config degisikligi tespit eder.',
      recommendedAction: 'Yapilan degisiklikleri derhal inceleyin. Admin kimligini dogrulayin. Gerekirse degisiklikleri geri alin. Oturumu sonlandirin.',
    },
  },
  {
    code: 'IPS_THEN_OUTBOUND',
    name: 'IPS Sonrasi Disari Baglanti',
    description: 'IPS saldiri alarmi tetiklenen hedef IP den disariya baglanti tespit edildi. Post-exploitation (basarili sizma) gostergesi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: ['IPS_CRITICAL_ALERT', 'MULTI_SECURITY_EVENTS'],
        lookbackMinutes: 30,
        secondaryLogtype: 'traffic',
        secondaryFilter: 'action == accept',
        matchField: 'destIp',
      },
      description: 'IPS alarmi tetiklenen hedef IP nin disariya trafik gonderip gondermedigini kontrol eder. Basarili sizma ve C2 haberlesme gostergesi.',
      recommendedAction: 'Hedef sistemi derhal izole edin. Disari giden trafigi analiz edin (C2 suphesi). Full malware taramasi yapin. Forensic inceleme basla.',
    },
  },
  {
    code: 'WEBBLOCK_THEN_TUNNEL',
    name: 'Web Engeli Sonrasi DNS Tuneli',
    description: 'WebFilter tarafindan engellenen hosttan DNS tunelleme aktivitesi tespit edildi. Guvenlik atlatma denemesi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'dns',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 30,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: ['WEBFILTER_HIGH_RISK', 'DNS_MALICIOUS'],
        lookbackMinutes: 30,
        secondaryLogtype: 'dns',
        secondaryFilter: 'qtype == TXT or qtype == NULL or qname like %.%',
        matchField: 'sourceIp',
      },
      description: 'WebFilter veya DNS engeli alan hosttan devam eden DNS tunelleme aktivitesi tespit eder. Guvenlik kontrollerini atlama girisimi.',
      recommendedAction: 'Hostu izole edin. DNS trafigini detayli analiz edin. Malware taramasi yapin. DNS tunelleme araci kalintilari arayin.',
    },
  },
  {
    code: 'VPN_GEO_THEN_EXFIL',
    name: 'Yeni Lokasyondan VPN + Veri Cikisi',
    description: 'Bilinmeyen lokasyondan VPN baglantisi ardindan yuksek hacimde veri transferi tespit edildi. Veri hirsizligi zinciri.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'traffic',
      filter: '',
      threshold: 1,
      timeWindowMinutes: 60,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: ['ADMIN_NEW_GEO', 'VPN_LOGIN_OFF_HOURS', 'VPN_NEW_USER'],
        lookbackMinutes: 60,
        secondaryLogtype: 'traffic',
        secondaryFilter: 'sentbyte > 10000000 or rcvdbyte > 10000000',
        matchField: 'sourceIp',
      },
      description: 'Suphe yaratan VPN baglantisi (yeni geo, mesai disi, yeni kullanici) ardindan buyuk veri transferi tespit eder.',
      recommendedAction: 'VPN oturumunu derhal sonlandirin. Transfer edilen verileri belirleyin. Kullanici hesabini kilitleyin. Veri sizintisi prosedurunu baslatin.',
    },
  },
  {
    code: 'MULTI_VECTOR_ATTACK',
    name: 'Coklu Vektor Saldirisi (APT)',
    description: 'Tek bir IP den 3 veya daha fazla farkli alarm tipi tespit edildi. Gelismis kalici tehdit (APT) gostergesi.',
    category: 'SOC_CORRELATION',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'event',
      filter: '',
      threshold: 3,
      timeWindowMinutes: 60,
      clientCheck: 'correlation',
      correlationRules: {
        precursorCodes: [
          'IPS_CRITICAL_ALERT', 'MALWARE_DETECTED', 'DNS_MALICIOUS', 'DNS_TUNNEL_SUSPECT',
          'WEBFILTER_HIGH_RISK', 'VPN_BRUTE_FORCE', 'ADMIN_BRUTE_FORCE', 'DATA_EXFIL_SUSPECT',
          'MULTI_SECURITY_EVENTS', 'DENIED_TRAFFIC_SPIKE',
        ],
        lookbackMinutes: 60,
        matchField: 'sourceIp',
        minDistinctCodes: 3,
      },
      description: 'Ayni kaynak IP den 3+ farkli guvenlik alarmi tetiklenmesini tespit eder. Koordineli veya cok vektorlu saldiri gostergesi (APT).',
      recommendedAction: 'Kaynak IP yi tum katmanlarda derhal engelleyin. Tum hedef sistemleri inceleyin. Lateral movement kontrol edin. Olay mudahale prosedurunu aktive edin. IoC listesine ekleyin.',
    },
  },
  // ============================================================================
  // VMWARE VCENTER ALARMS
  // ============================================================================
  {
    code: 'VM_POWERED_OFF',
    name: 'VM Beklenmedik Kapanma',
    description: 'Sanal makine son 15 dakikada kapandi. Sadece kullanici tarafindan yapilan kapanmalar alarm uretir (backup/servis hesaplari haric).',
    category: 'OPERATIONAL',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'powerState == poweredOff',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'vCenter Events API uzerinden VmPoweredOffEvent ve VmGuestShutdownEvent olaylarini izler. Backup/servis hesaplari filtrelenir.',
      recommendedAction: 'VM durumunu ve event loglarini kontrol edin. Graceful shutdown mu yoksa unexpected power-off mu oldugunu inceleyin. Gerekirse VM yi yeniden baslatin. Tekrarlayan kapanmalarda root cause analizi yapin.',
    },
  },
  {
    code: 'VM_CPU_CRITICAL',
    name: 'VM CPU Kritik Kullanim',
    description: 'Sanal makine CPU kullanimi %90 uzerinde. Performans sorunu veya kaynak yetersizligi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'cpuUsage > 90',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'VM CPU kullanim oranini izler. %90 ustune ciktiginda alarm uretir.',
      recommendedAction: 'VM uzerinde calisan surecleri kontrol edin. Gerekirse vCPU sayisini artirin veya load balancing yapin. Uygulamayi optimize edin.',
    },
  },
  {
    code: 'VM_MEMORY_CRITICAL',
    name: 'VM Bellek Kritik Kullanim',
    description: 'Sanal makine bellek kullanimi %90 uzerinde. Bellek yetersizligi veya memory leak.',
    category: 'OPERATIONAL',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'memoryUsage > 90',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'VM bellek kullanim oranini izler. %90 ustune ciktiginda alarm uretir.',
      recommendedAction: 'VM bellek kullanimini analiz edin. Memory leak kontrolu yapin. Gerekirse RAM artirin. Uygulama restart gerekebilir.',
    },
  },
  {
    code: 'HOST_DISCONNECTED',
    name: 'ESXi Host Baglanti Kesildi',
    description: 'ESXi host ile vCenter baglantisi kesildi. Kritik altyapi sorunu.',
    category: 'OPERATIONAL',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 5,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'connectionState != connected',
      threshold: 1,
      timeWindowMinutes: 5,
      description: 'ESXi host baglanti durumunu izler. Disconnected veya notResponding durumunu tespit eder.',
      recommendedAction: 'Host fiziksel durumunu kontrol edin. Network baglantisini dogrulayin. vCenter agent durumunu kontrol edin. HA failover durumunu izleyin.',
    },
  },
  {
    code: 'HOST_CPU_CRITICAL',
    name: 'Host CPU Kritik Kullanim',
    description: 'ESXi host CPU kullanimi %85 uzerinde. VM performansi etkilenebilir.',
    category: 'OPERATIONAL',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'hostCpuUsage > 85',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'ESXi host CPU kullanim oranini izler. %85 ustune ciktiginda alarm uretir.',
      recommendedAction: 'Host uzerindeki VM dagilimini kontrol edin. vMotion ile bazi VM leri diger hostlara tasiyin. DRS ayarlarini gozden gecirin.',
    },
  },
  {
    code: 'HOST_MEMORY_CRITICAL',
    name: 'Host Bellek Kritik Kullanim',
    description: 'ESXi host bellek kullanimi %90 uzerinde. Memory ballooning veya swapping baslar.',
    category: 'OPERATIONAL',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'hostMemoryUsage > 90',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'ESXi host bellek kullanim oranini izler. %90 ustune ciktiginda alarm uretir.',
      recommendedAction: 'Ballooning ve swap durumunu kontrol edin. VM leri diger hostlara tasiyin. Bellek reservation ayarlarini gozden gecirin.',
    },
  },
  {
    code: 'DATASTORE_SPACE_LOW',
    name: 'Datastore Alan Dusuk',
    description: 'Datastore bos alani %15 altina dustu. Kapasite planlama gerekli.',
    category: 'OPERATIONAL',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 60,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'datastoreFreePercent < 15',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Datastore bos alan yuzdesini izler. %15 altina dustugunde alarm uretir.',
      recommendedAction: 'Gereksiz snapshot lari silin. Eski template ve ISO dosyalarini temizleyin. Storage vMotion ile bazi VM leri tasiyin. Kapasite artisi planlayin.',
    },
  },
  {
    code: 'DATASTORE_SPACE_CRITICAL',
    name: 'Datastore Alan Kritik',
    description: 'Datastore bos alani %5 altina dustu. Acil mudahale gerekli.',
    category: 'OPERATIONAL',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'datastoreFreePercent < 5',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'Datastore bos alan yuzdesini izler. %5 altina dustugunde kritik alarm uretir.',
      recommendedAction: 'ACIL: Snapshot lari derhal silin. Gereksiz dosyalari temizleyin. VM leri baska datastore a tasiyin. Yeni storage ekleyin.',
    },
  },
  // ============================================================================
  // VMWARE - CLUSTER & HA RISKS
  // ============================================================================
  {
    code: 'CLUSTER_HA_RISK',
    name: 'HA Failover Kapasitesi Yetersiz',
    description: '1 host down senaryosunda CPU veya RAM kapasitesi %100 asacak. HA failover riski.',
    category: 'OPERATIONAL',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 120,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'haFailoverRisk == true',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'HA cluster da 1 host kaybi durumunda kalan hostlarin CPU veya RAM kapasitesinin %100 u asip asmayacagini kontrol eder. Asarsa kritik alarm uretir.',
      recommendedAction: 'ACIL: Cluster a yeni host ekleyin veya VM leri baska cluster a tasiyin. HA admission control ayarlarini gozden gecirin. VM resource ayarlarini optimize edin.',
    },
  },
  {
    code: 'SNAPSHOT_DISK_GROWTH',
    name: 'Snapshot Disk Sismesi',
    description: 'Snapshot disk buyumesi son 24 saatte %20 yi asti. Disk alani riski.',
    category: 'OPERATIONAL',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 240,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'snapshotGrowthPercent24h > 20',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'VM snapshot larinin son 24 saatteki disk buyume oranini izler. %20 yi asarsa kritik alarm uretir.',
      recommendedAction: 'Snapshot lari derhal kontrol edin. Eski ve gereksiz snapshot lari silin. Snapshot retention policy gozden gecirin. Datastore bos alanini kontrol edin.',
    },
  },
  {
    code: 'DRS_IMBALANCE',
    name: 'DRS Dengesizligi',
    description: 'Cluster icinde host CPU farki %25 i asti. DRS load balancing calismadi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 60,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'drsImbalance > 25',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Cluster daki host lar arasinda CPU kullanim farkini izler. %25 ten buyukse DRS dengesizligi alarmini uretir.',
      recommendedAction: 'DRS ayarlarini kontrol edin (automation level, migration threshold). VM affinity/anti-affinity kurallari gozden gecirin. Manuel vMotion ile dengeleme yapin.',
    },
  },
  // ============================================================================
  // VMWARE - SECURITY & OPERATIONS
  // ============================================================================
  {
    code: 'ESXI_MAINTENANCE_OUT_OF_HOURS',
    name: 'Mesai Disi Maintenance Mode',
    description: 'ESXi host 22:00-06:00 arasi maintenance mode a alindi. MITRE Impact/Persistence.',
    category: 'SECURITY',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 30,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'maintenanceMode == true',
      threshold: 1,
      timeWindowMinutes: 15,
      clientCheck: 'off-hours',
      description: 'ESXi host un maintenance mode a alinmasini izler. 22:00-06:00 arasi olanlar kritik alarm uretir. MITRE ATT&CK: Impact ve Persistence kategorisinde.',
      recommendedAction: 'ACIL: Maintenance i kim yapti kontrol edin. Yetkisiz mudahale ise host u inceleyin. Change management sureci takip edilmis mi dogrulayin.',
    },
  },
  {
    code: 'VM_DELETED',
    name: 'VM Silindi',
    description: 'VM delete event tespit edildi. SOC entegrasyonu icin altin alarm.',
    category: 'SECURITY',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 15,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'vmDeleted == true',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'VM silme islemini izler. Hangi VM, kim tarafindan, ne zaman silindigini kaydeder. SOC forensics icin kritik veri.',
      recommendedAction: 'ACIL: VM i kim sildi kontrol edin. Yetkisiz islem ise forensic inceleme baslatın. Yedekten geri yukleme gerekebilir. Change ticket kontrol edin.',
    },
  },
  {
    code: 'CONFIG_CHANGE_AFTER_HOURS',
    name: 'Mesai Disi Konfig Degisikligi',
    description: 'Host veya Cluster config degisikligi mesai disi yapildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'configChange == true',
      threshold: 1,
      timeWindowMinutes: 15,
      clientCheck: 'off-hours',
      description: 'ESXi host veya vCenter cluster ayarlarindaki degisiklikleri izler. 18:00-08:00 ve hafta sonu degisiklikleri orta seviye alarm uretir.',
      recommendedAction: 'Degisiklik kim tarafindan yapildi kontrol edin. Change management sureci takip edildi mi dogrulayin. Kritik config degisimleri varsa geri alin.',
    },
  },
  // ============================================================================
  // VMWARE - LIFECYCLE EVENTS
  // ============================================================================
  {
    code: 'VM_CREATED',
    name: 'VM Olusturuldu',
    description: 'Yeni sanal makine olusturuldu. SOC entegrasyonu ve envanter takibi icin.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 15,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'vmCreated == true',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Yeni VM olusturma islemini izler. Hangi VM, kim tarafindan, ne zaman olusturuldugunu kaydeder.',
      recommendedAction: 'VM i kimin olustuurdugunu kontrol edin. Change ticket ile eslestirin. Resource allocation ayarlarini gozden gecirin.',
    },
  },
  {
    code: 'VM_POWERED_ON',
    name: 'VM Acildi',
    description: 'Sanal makine power on edildi. Beklenmeyen VM baslatma izleme.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 15,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'powerState == poweredOn',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'VM power-on islemlerini izler. Normal baslatmalari kaydeder.',
      recommendedAction: 'VM baslatma isleminin planli olup olmadigini kontrol edin. Boot time ve startup service lerini izleyin.',
    },
  },
  {
    code: 'VM_POWERED_ON_OFF_HOURS',
    name: 'Mesai Disi VM Baslatma',
    description: 'Calisma saatleri disinda VM power-on edildi. Yetkisiz mudahale riski.',
    category: 'SECURITY',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 30,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'powerState == poweredOn',
      threshold: 1,
      timeWindowMinutes: 10,
      clientCheck: 'off-hours',
      description: '18:00-08:00 arasi veya hafta sonu VM baslatma islemlerini tespit eder. Yetkisiz erisim veya planli olmayan mudahale gostergesi.',
      recommendedAction: 'ACIL: VM i kim baslatti kontrol edin. Change management sureci takip edilmis mi dogrulayin. Yetkisiz ise VM i kapatip inceleyin.',
    },
  },
  {
    code: 'VM_RESTARTED',
    name: 'VM Yeniden Baslatildi',
    description: 'VM restart edildi. Guvenlik patch veya beklenmeyen sistem hatasi olabilir.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 30,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'vmRestarted == true',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'VM restart islemlerini izler. Planli veya beklenmeyen yeniden baslatmalari kaydeder.',
      recommendedAction: 'Restart nedenini kontrol edin. Windows Update, patch veya crash loglarini inceleyin. Tekrarlayan restart varsa root cause analizi yapin.',
    },
  },
  {
    code: 'SNAPSHOT_CREATED',
    name: 'Snapshot Olusturuldu',
    description: 'VM snapshot alindi. Disk alani takibi ve yedekleme sureci izleme. Veeam backup snapshot lari haric tutulur.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 75, // Must be > timeWindowMinutes to prevent duplicate triggers
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'snapshotCreated == true',
      threshold: 1,
      timeWindowMinutes: 60, // Increased from 15 to catch snapshots within 1-hour window
      description: 'Snapshot olusturma islemlerini izler. Hangi VM, snapshot adi ve boyutunu kaydeder. Veeam kullanici ve "VEEAM BACKUP TEMPORARY SNAPSHOT" iceren snapshot lar filtrelenir.',
      recommendedAction: 'Snapshot amacini kontrol edin (backup, test, patch oncesi). Datastore bos alanini dogrulayin. Snapshot retention policy hatirlatın.',
    },
  },
  {
    code: 'SNAPSHOT_DELETED',
    name: 'Snapshot Silindi',
    description: 'VM snapshot silindi veya commit edildi. Disk alani kurtarma islemi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 30,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'snapshotDeleted == true',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'Snapshot silme/commit islemlerini izler. Disk alani kurtarma ve cleanup operasyonlarini kaydeder.',
      recommendedAction: 'Snapshot silme isleminin tamamlandigini kontrol edin. Datastore bos alaninin arttigini dogrulayin. Consolidation gerekiyorsa yapin.',
    },
  },
  {
    code: 'SNAPSHOT_REVERTED',
    name: 'Snapshot Geri Yuklendi',
    description: 'VM snapshot a geri yuklendi. Kritik rollback islemi tespit edildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 15,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'snapshotReverted == true',
      threshold: 1,
      timeWindowMinutes: 10,
      description: 'Snapshot revert islemlerini izler. VM nin onceki duruma geri alinmasini tespit eder.',
      recommendedAction: 'Revert nedenini inceleyin (patch geri alma, test hatasi, ransomware recovery). VM durumunu dogrulayin. Backup guncellemesi gerekebilir.',
    },
  },
  {
    code: 'SNAPSHOT_REVERTED_OFF_HOURS',
    name: 'Mesai Disi Snapshot Geri Yukleme',
    description: 'Calisma saatleri disinda snapshot revert yapildi. Ransomware recovery veya yetkisiz mudahale.',
    category: 'SECURITY',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 15,
    notifyEmail: true,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'snapshotReverted == true',
      threshold: 1,
      timeWindowMinutes: 10,
      clientCheck: 'off-hours',
      description: '18:00-08:00 arasi veya hafta sonu snapshot revert islemlerini tespit eder. Ransomware recovery, yetkisiz mudahale veya kritik sistem sorunu gostergesi.',
      recommendedAction: 'ACIL: Revert i kim yapti ve nedenini kontrol edin. Ransomware suphesi varsa forensic inceleme baslatın. Change management kontrolu yapin.',
    },
  },
  {
    code: 'MULTIPLE_SNAPSHOTS',
    name: 'Coklu Snapshot Zinciri',
    description: 'Tek bir VM de 3 ten fazla snapshot tespit edildi. Performans ve disk riski.',
    category: 'OPERATIONAL',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 120,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'snapshotCount > 3',
      threshold: 1,
      timeWindowMinutes: 60,
      description: 'Ayni VM de 3 ten fazla snapshot zincirini tespit eder. Performans dususu ve disk alani riski olusturur.',
      recommendedAction: 'Gereksiz snapshot lari silin. Snapshot consolidation yapin. Snapshot retention policy hatirlatın. Sadece gerekli snapshot lari tutun.',
    },
  },
  {
    code: 'VM_CLONED',
    name: 'VM Klonlandi',
    description: 'VM clone islemi tespit edildi. Kapasite planlamasi ve lisans takibi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 30,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'vmCloned == true',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'VM cloning islemlerini izler. Kaynak VM ve hedef VM bilgilerini kaydeder.',
      recommendedAction: 'Clone amacini kontrol edin (test, dev, prod replica). Lisans gereksinimlerini dogrulayin. Resource allocation kontrolu yapin.',
    },
  },
  {
    code: 'VM_MIGRATED',
    name: 'VM Tasindi (vMotion/Storage vMotion)',
    description: 'VM baska host veya datastore a tasindi. Migration islemi kaydedildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_INFO',
    cooldownMinutes: 30,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'vmMigrated == true',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'vMotion veya Storage vMotion islemlerini izler. Kaynak ve hedef host/datastore bilgilerini kaydeder.',
      recommendedAction: 'Migration basarili tamamlandi mi kontrol edin. VM performansini dogrulayin. DRS otomatik migration ise policy yi gozden gecirin.',
    },
  },
  {
    code: 'VM_RECONFIGURED',
    name: 'VM Konfigurasyon Degisikligi',
    description: 'VM kaynak ayarlari degistirildi (CPU, RAM, disk). Kapasite planlamasi takibi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'vmReconfigured == true',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'VM kaynak degisikliklerini izler (vCPU, RAM, disk boyutu, network adapter). Hot-add/remove islemleri dahil.',
      recommendedAction: 'Degisiklik nedenini ve kim tarafindan yapildigini kontrol edin. Host kaynaklarinin yeterli oldugunu dogrulayin. Lisans etkisi varsa kontrol edin.',
    },
  },
  {
    code: 'VM_SUSPENDED',
    name: 'VM Suspend Edildi',
    description: 'VM suspend (askiya alma) durumuna alindi. Bellek dump disk e yazildi.',
    category: 'OPERATIONAL',
    severity: 'ALARM_LOW',
    cooldownMinutes: 30,
    notifyEmail: false,
    detectionLogic: {
      logtype: 'vmware',
      filter: 'powerState == suspended',
      threshold: 1,
      timeWindowMinutes: 15,
      description: 'VM suspend islemlerini izler. Bellek durumu disk e kaydedilir ve VM durdurulur.',
      recommendedAction: 'Suspend nedenini kontrol edin. Uzun sure suspended kalan VM ler varsa resume veya shutdown yapin. Datastore alanini kontrol edin.',
    },
  },
  // ============================================================================
  // NEW FORTIGATE CONFIG ALARMS - 2024
  // ============================================================================
  {
    code: 'NEW_VIP',
    name: 'Yeni Virtual IP (DNAT) Olusturuldu',
    description: 'Yeni Virtual IP tanimlandi. Dahili sunuculari disariya acar, kritik guvenlik etkisi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 5,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.vip% and action == Add',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Virtual IP (DNAT) olusturma islemlerini tespit eder. VIP ler dahili sunuculari internet e acar ve saldiri yuzeyi olusturur.',
      recommendedAction: 'VIP in yetkili degisiklik olup olmadigini dogrulayin. Acilan portu ve dahili sunucuyu kontrol edin. SSL inspection ve IPS korumasi aktif mi kontrol edin.',
    },
  },
  {
    code: 'NEW_ADMIN_USER',
    name: 'Yeni Admin Kullanici Olusturuldu',
    description: 'FortiGate a yeni admin kullanici eklendi. Yetkisiz erisim riski.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_CRITICAL',
    cooldownMinutes: 5,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %system.admin% and action == Add',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Yeni admin kullanici olusturma islemlerini tespit eder. Yetkisiz admin hesaplari kritik guvenlik riski olusturur.',
      recommendedAction: 'Yeni admin hesabinin yetkili olup olmadigini dogrulayin. Verilen yetkileri kontrol edin. 2FA aktif edildiginden emin olun.',
    },
  },
  {
    code: 'ADMIN_PASSWORD_CHANGED',
    name: 'Admin Sifre Degisikligi',
    description: 'Admin kullanici sifresi degistirildi. Hesap guvenligi etkisi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %system.admin% and logdesc like %password%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Admin sifre degisikliklerini tespit eder. Yetkisiz sifre degisikligi hesap ele gecirme gostergesi olabilir.',
      recommendedAction: 'Sifre degisikliginin yetkili oldugunu dogrulayin. Admin ile iletisime gecin. Suphe varsa hesabi kilitleyin.',
    },
  },
  {
    code: 'SERVICE_GROUP_CHANGED',
    name: 'Servis Grubu Degisikligi',
    description: 'Firewall servis grubu uzerinde ekleme, silme veya duzenleme tespit edildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.service.group%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Servis grubu degisikliklerini tespit eder. Grup degisiklikleri birden fazla policy yi etkileyebilir.',
      recommendedAction: 'Hangi servis grubunun degistigini kontrol edin. Etkilenen tum policy leri inceleyin. Change management onayini dogrulayin.',
    },
  },
  {
    code: 'NAT_POLICY_CHANGED',
    name: 'NAT Politika Degisikligi',
    description: 'Central NAT veya IP Pool yapilandirmasi degistirildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and (cfgpath like %firewall.central-snat% or cfgpath like %firewall.ippool%)',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Central SNAT ve IP pool degisikliklerini tespit eder. NAT degisiklikleri trafik yonlendirmesini etkiler.',
      recommendedAction: 'NAT degisikliginin amacini dogrulayin. Etkilenen trafik akislarini kontrol edin. IP pool exhaustion riski var mi inceleyin.',
    },
  },
  {
    code: 'IPSEC_TUNNEL_CHANGED',
    name: 'IPsec VPN Yapilandirma Degisikligi',
    description: 'IPsec Phase1 veya Phase2 yapilandirmasi degistirildi. Site-to-site VPN etkisi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and (cfgpath like %vpn.ipsec.phase1% or cfgpath like %vpn.ipsec.phase2%)',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'IPsec VPN yapilandirma degisikliklerini tespit eder. Saha arasi baglantilari etkiler.',
      recommendedAction: 'VPN degisikliginin yetkili oldugunu dogrulayin. Etkilenen tunnel larin durumunu kontrol edin. Remote site ile koordinasyon saglayin.',
    },
  },
  {
    code: 'SSL_VPN_SETTINGS_CHANGED',
    name: 'SSL-VPN Ayarlari Degisikligi',
    description: 'SSL-VPN portal, realm veya settings yapilandirmasi degistirildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %vpn.ssl%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'SSL-VPN yapilandirma degisikliklerini tespit eder. Remote erisim guvenligini etkiler.',
      recommendedAction: 'SSL-VPN degisikliginin yetkili oldugunu dogrulayin. Portal ve realm ayarlarini kontrol edin. Kullanici erisimlerini test edin.',
    },
  },
  {
    code: 'SCHEDULE_OBJECT_CHANGED',
    name: 'Zaman Objesi Degisikligi',
    description: 'Firewall schedule objesi degistirildi. Policy zamanlama etkisi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.schedule%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Schedule objesi degisikliklerini tespit eder. Policy uygulanma zamanlarini etkiler.',
      recommendedAction: 'Schedule degisikliginin hangi policy leri etkiledigini kontrol edin. Is saatleri disinda aktif olacak kurallari inceleyin.',
    },
  },
  {
    code: 'POLICY_DISABLED',
    name: 'Firewall Politikasi Devre Disi',
    description: 'Bir veya daha fazla firewall politikasi devre disi birakildi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.policy% and logdesc like %status%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Devre disi birakilan firewall policy lerini tespit eder. Guvenlik boslugu olusabilir.',
      recommendedAction: 'Hangi policy nin devre disi birakildigini kontrol edin. Guvenlik etkisini degerlendiriniz. Gecici mi kalici mi belirleyin.',
    },
  },
  {
    code: 'INTERFACE_CONFIG_CHANGED',
    name: 'Interface Yapilandirma Degisikligi',
    description: 'Network interface ayarlari degistirildi. IP, VLAN veya mode degisikligi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %system.interface%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Interface yapilandirma degisikliklerini tespit eder. IP, VLAN, mode, MTU vb. degisiklikleri kapsar.',
      recommendedAction: 'Interface degisikliginin amacini dogrulayin. Network baglantisini test edin. HA senkronizasyonunu kontrol edin.',
    },
  },
  {
    code: 'SNAT_POOL_CHANGED',
    name: 'SNAT IP Pool Degisikligi',
    description: 'Source NAT IP pool yapilandirmasi degistirildi.',
    category: 'RISK_ANOMALY',
    severity: 'ALARM_MEDIUM',
    cooldownMinutes: 30,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and cfgpath like %firewall.ippool%',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'SNAT IP pool degisikliklerini tespit eder. Dis baglantilarda kullanilan IP leri etkiler.',
      recommendedAction: 'IP pool degisikligini dogrulayin. Exhaustion riski var mi kontrol edin. External servislerle IP degisikligini koordine edin.',
    },
  },
  {
    code: 'AUTH_SERVER_CHANGED',
    name: 'Authentication Server Degisikligi',
    description: 'LDAP, RADIUS veya TACACS+ sunucu yapilandirmasi degistirildi.',
    category: 'CONFIG_ACCESS',
    severity: 'ALARM_HIGH',
    cooldownMinutes: 15,
    detectionLogic: {
      logtype: 'event',
      filter: 'subtype == system and logdesc like %attribute% and (cfgpath like %user.ldap% or cfgpath like %user.radius% or cfgpath like %user.tacacs%)',
      threshold: 1,
      timeWindowMinutes: 30,
      description: 'Authentication sunucu yapilandirma degisikliklerini tespit eder. Kullanici dogrulama sistemlerini etkiler.',
      recommendedAction: 'Auth server degisikligini dogrulayin. Kullanici girislerini test edin. Failover sunucu yapilandirmasini kontrol edin.',
    },
  },
];
