/**
 * Alarm Suppression Engine
 * 
 * Filters noisy infrastructure events to prevent false-positive alerts,
 * while still allowing real anomalies to be detected.
 * 
 * Supports suppression rules for:
 * - VMware automation events (vMotion, snapshots, backups)
 * - Backup tool events (Veeam, etc.)
 * - Service account activity
 * - Time-based maintenance windows
 * - Device/port-based suppression
 */

export interface SuppressionEvent {
  // Core identifiers
  userName?: string;
  vmName?: string;
  hostName?: string;
  deviceName?: string;
  portName?: string;
  
  // Event metadata
  eventType?: string;
  message?: string;
  source?: string;
  alarmCode?: string;
  
  // Timestamp for time-based rules
  timestamp?: string | Date;
}

export interface SuppressionRule {
  id: string;
  name: string;
  description?: string;
  
  // Which alarm codes this rule applies to (empty = all)
  alarmCodes: string[];
  
  // Event type matching (empty = all)
  eventTypes?: string[];
  
  // Keyword matching (case-insensitive)
  keywords?: string[];
  
  // Field-based matching
  field?: 'userName' | 'vmName' | 'hostName' | 'deviceName' | 'portName';
  fieldValues?: string[];
  
  // Time-based suppression
  timeWindow?: {
    startHour: number;   // 0-23
    endHour: number;     // 0-23
    days?: number[];     // 0=Sunday, 1=Monday, ..., 6=Saturday (empty = all days)
  };
  
  // Enable/disable
  enabled: boolean;
  
  // Reason for suppression (logged for audit)
  reason?: string;
}

/**
 * Default VMware suppression rules
 */
export const VMWARE_SUPPRESSION_RULES: SuppressionRule[] = [
  {
    id: 'vmware-automation',
    name: 'VMware Automation Services',
    description: 'Suppress events from VMware automation services (EAM, DRS, etc.)',
    alarmCodes: ['VM_MIGRATED', 'VM_CLONED', 'VM_RECONFIGURED', 'VM_SUSPENDED'],
    keywords: [
      'com.vmware.vim.eam',      // ESX Agent Manager
      'com.vmware.vpxd',         // vCenter Server
      'drs.',                    // DRS automation
      'vmware',
      'vcenter',
    ],
    enabled: true,
    reason: 'Automated VMware operation',
  },
  {
    id: 'veeam-backup',
    name: 'Veeam Backup & Replication',
    description: 'Suppress events generated by Veeam backup jobs',
    alarmCodes: ['VM_SNAPSHOT_CREATE', 'VM_SNAPSHOT_DELETE', 'VM_BACKUP_STARTED'],
    keywords: [
      'veeam',
      'veeam backup',
      'veeam replica',
      'veeam agent',
      'veeam backup & replication',
      'vbr',
    ],
    enabled: true,
    reason: 'Veeam backup operation',
  },
  {
    id: 'migration-events',
    name: 'VM Migration Events',
    description: 'Suppress all vMotion/Storage vMotion events (usually automated)',
    alarmCodes: ['VM_MIGRATED'],
    eventTypes: ['VmMigratedEvent', 'VmMigrationEvent', 'VmRelocatedEvent'],
    enabled: true, // Enabled to suppress ALL migrations
    reason: 'VM migration (vMotion)',
  },
  {
    id: 'snapshot-operations',
    name: 'Snapshot Operations',
    description: 'Suppress snapshot create/delete events (usually automated by backup tools)',
    alarmCodes: ['VM_SNAPSHOT_CREATE', 'VM_SNAPSHOT_DELETE', 'MULTIPLE_SNAPSHOTS'],
    keywords: [
      'veeam',
      'backup',
      'automated',
      'scheduled',
    ],
    enabled: false, // Disabled by default - enable to suppress ALL snapshot events
    reason: 'Snapshot operation',
  },
];

/**
 * Suppression Engine
 */
export class SuppressionEngine {
  private rules: SuppressionRule[];

  constructor(rules: SuppressionRule[] = []) {
    this.rules = rules;
  }

  /**
   * Add suppression rules
   */
  addRules(rules: SuppressionRule[]): void {
    this.rules.push(...rules);
  }

  /**
   * Get all active rules
   */
  getRules(): SuppressionRule[] {
    return this.rules.filter(r => r.enabled);
  }

  /**
   * Enable/disable a specific rule
   */
  setRuleEnabled(ruleId: string, enabled: boolean): boolean {
    const rule = this.rules.find(r => r.id === ruleId);
    if (!rule) return false;
    rule.enabled = enabled;
    return true;
  }

  /**
   * Check if an event should be suppressed
   * @returns Suppression result with matched rule (if any)
   */
  shouldSuppress(event: SuppressionEvent): {
    suppressed: boolean;
    rule?: SuppressionRule;
    reason?: string;
  } {
    const enabledRules = this.getRules();

    for (const rule of enabledRules) {
      if (this.matchesRule(event, rule)) {
        return {
          suppressed: true,
          rule,
          reason: rule.reason,
        };
      }
    }

    return { suppressed: false };
  }

  /**
   * Filter an array of events, removing suppressed ones
   */
  filterEvents(events: SuppressionEvent[]): {
    kept: SuppressionEvent[];
    suppressed: SuppressionEvent[];
    suppressionStats: Record<string, number>;
  } {
    const kept: SuppressionEvent[] = [];
    const suppressed: SuppressionEvent[] = [];
    const suppressionStats: Record<string, number> = {};

    for (const event of events) {
      const result = this.shouldSuppress(event);
      if (result.suppressed && result.rule) {
        suppressed.push(event);
        suppressionStats[result.rule.id] = (suppressionStats[result.rule.id] || 0) + 1;
      } else {
        kept.push(event);
      }
    }

    return { kept, suppressed, suppressionStats };
  }

  /**
   * Check if an event matches a specific rule
   */
  private matchesRule(event: SuppressionEvent, rule: SuppressionRule): boolean {
    // Check alarm code filter
    if (rule.alarmCodes.length > 0) {
      if (!event.alarmCode || !rule.alarmCodes.includes(event.alarmCode)) {
        return false;
      }
    }

    // Check event type filter
    if (rule.eventTypes && rule.eventTypes.length > 0) {
      if (!event.eventType || !rule.eventTypes.includes(event.eventType)) {
        return false;
      }
    }

    // Check keyword matching (case-insensitive)
    if (rule.keywords && rule.keywords.length > 0) {
      const userName = (event.userName || '').toLowerCase();
      const message = (event.message || '').toLowerCase();
      const eventType = (event.eventType || '').toLowerCase();

      const matchesKeyword = rule.keywords.some(kw => {
        const keyword = kw.toLowerCase();
        return (
          userName.includes(keyword) ||
          message.includes(keyword) ||
          eventType.includes(keyword)
        );
      });

      if (!matchesKeyword) {
        return false;
      }
    }

    // Check field-based matching
    if (rule.field && rule.fieldValues && rule.fieldValues.length > 0) {
      const fieldValue = event[rule.field];
      if (!fieldValue || !rule.fieldValues.includes(fieldValue)) {
        return false;
      }
    }

    // Check time window
    if (rule.timeWindow) {
      const timestamp = event.timestamp ? new Date(event.timestamp) : new Date();
      const hour = timestamp.getHours();
      const day = timestamp.getDay();

      // Check hour range
      const { startHour, endHour } = rule.timeWindow;
      if (startHour <= endHour) {
        // Normal range (e.g., 9-17)
        if (hour < startHour || hour >= endHour) {
          return false;
        }
      } else {
        // Overnight range (e.g., 22-6)
        if (hour < startHour && hour >= endHour) {
          return false;
        }
      }

      // Check day of week
      if (rule.timeWindow.days && rule.timeWindow.days.length > 0) {
        if (!rule.timeWindow.days.includes(day)) {
          return false;
        }
      }
    }

    return true;
  }

  /**
   * Get suppression statistics
   */
  getStats(): {
    totalRules: number;
    enabledRules: number;
    rules: Array<{
      id: string;
      name: string;
      enabled: boolean;
      alarmCodes: string[];
    }>;
  } {
    return {
      totalRules: this.rules.length,
      enabledRules: this.rules.filter(r => r.enabled).length,
      rules: this.rules.map(r => ({
        id: r.id,
        name: r.name,
        enabled: r.enabled,
        alarmCodes: r.alarmCodes,
      })),
    };
  }
}

/**
 * Create default suppression engine with VMware rules
 */
export function createDefaultSuppressionEngine(): SuppressionEngine {
  return new SuppressionEngine([...VMWARE_SUPPRESSION_RULES]);
}
