-- AddColumn to rooms table
ALTER TABLE "rooms" ADD COLUMN "width" DOUBLE PRECISION;
ALTER TABLE "rooms" ADD COLUMN "depth" DOUBLE PRECISION;
ALTER TABLE "rooms" ADD COLUMN "height" DOUBLE PRECISION;

-- AddColumn to racks table
ALTER TABLE "racks" ADD COLUMN "coordX" DOUBLE PRECISION;
ALTER TABLE "racks" ADD COLUMN "coordY" DOUBLE PRECISION;
ALTER TABLE "racks" ADD COLUMN "coordZ" DOUBLE PRECISION;
ALTER TABLE "racks" ADD COLUMN "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0;
